### ISSUE TITLE
Can't import Span, Arrow, NormalHead from Bokeh

### ISSUE THREAD

**Issue by cenyuzhang** [IBM/starcraft2-replay-analysis#14]
When trying to run in DSX, got the following error:

ImportError: cannot import name Span

Same error for Arrow, and NormalHead

This is under the section of "Visualize and compare replay events"

**Comment by markstur** [comment]
Could you try removing bokeh from the current pip install command and add and run this line?
!pip install --upgrade bokeh==0.12.5
Then you might need to restart the kernel.  The import should work once bokeh 0.12.5 is installed.
Please comment if this fixes the problem.  Thanks for reporting it.

**Comment by cenyuzhang** [comment]
It fixed the problems. Thanks a lot for the quick response!

**Comment by stevemart** [comment]
thanks for the tip @markstur and for verifying the fix @cenyuzhang ! closing the issue.
