### ISSUE TITLE
Importing Replay file broken

### ISSUE THREAD

**Issue by ywarraich** [IBM/starcraft2-replay-analysis#24]
When importing the sample replay file, the option for "Import StringIO" does not show under "Insert the code". Look like COS is interpretting the input file incorrectly.

<img width="264" alt="image" src="https://user-images.githubusercontent.com/27869165/36001071-1b3afb24-0cf3-11e8-8682-f2be0bb46eae.png">

Demo can not be completed without fixing this.
Appreciate your attention to this.
Thanks!

**Comment by cpcunningham** [comment]
Hi @ywarraich - Can you us more detail on what you are doing. Maybe  you could post some of the demo code.
